django_site_newspaper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
     path("admin/", admin.site.urls),
     path("", include("tracker.urls", namespace="tracker")),
     path("accounts/", include("django.contrib.auth.urls"))
 ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from tracker.views import (
    index,
    TopicListView,
    TopicDetailView,
    RedactorListView,
    RedactorDetailView,
    NewspaperListView,
    NewspaperDetailView,
    TopicCreateView,
    NewspaperCreateView,
    TopicUpdateView,
    NewspaperUpdateView,
    TopicDeleteView,
    NewspaperDeleteView,
    RedactorCreateView,
    RedactorUpdateView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list"
     ),
    path(
        "topics/<int:pk>/",
        TopicDetailView.as_view(),
        name="topic-detail"
     ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
     ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
     ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list"
     ),
    path(
         "newspapers/<int:pk>/",
         NewspaperDetailView.as_view(),
         name="newspaper-detail"
     ),
    path(
         "topics/create/",
         TopicCreateView.as_view(),
         name="topic-create"
     ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update"
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update"
    ),
]

urlpatterns += staticfiles_urlpatterns()

app_name = "tracker"

tracker/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


from django_site_newspaper.settings import AUTH_USER_MODEL


class Topic(models.Model):
    name = models.CharField(max_length=31)

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    years_of_experience = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.username


class Newspaper(models.Model):
    title = models.CharField(max_length=63, unique=True)
    content = models.TextField()
    publish_date = models.DateField(null=True, blank=True)
    topic = models.ManyToManyField(Topic, related_name="newspapers", blank=True)
    publishers = models.ManyToManyField(
        AUTH_USER_MODEL,
        related_name="newspapers",
        blank=True
    )

    class Meta:
        ordering = ["-publish_date"]

    def __str__(self):
        return f"{self.title} date: {self.publish_date}"

tracker/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError
from tracker.models import Redactor, Newspaper, Topic


class RedactorForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name", "years_of_experience")

    def clean_years_of_experience(self):
        years_of_experience = self.cleaned_data["years_of_experience"]
        if years_of_experience < 0:
            raise ValidationError(
                f"Years of experience cannot be less than zero ;)"
            )
        return years_of_experience


class NewspaperForm(forms.ModelForm):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    topic = forms.ModelMultipleChoiceField(
        queryset=Topic.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    text = {"placeholder": "YYYY-MM-DD"}
    publish_date = forms.DateField(widget=forms.TextInput(attrs=text), required=False)
    title = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Newspaper
        fields = "__all__"


class SearchForm(forms.Form):
    text = {"placeholder": "press Enter for searching"}
    search_text = forms.CharField(max_length=63,
                                  required=False,
                                  label="",
                                  widget=forms.TextInput(attrs=text))


class NewspaperFilterForm(forms.Form):
    publishers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label="Redactors"
    )
    topic = forms.ModelMultipleChoiceField(
        queryset=Topic.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label="Topics"
    )

tracker/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from .forms import RedactorForm, SearchForm, NewspaperForm, NewspaperFilterForm
from .models import Topic, Newspaper, Redactor


def index(request):
    context = {}
    return render(request, "tracker/index.html", context=context)


class TopicListView(generic.ListView):
    model = Topic

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        search_text = self.request.GET.get("search_text", "")
        text = {"search_text": search_text}
        context["search_form"] = SearchForm(initial=text)
        context["leaders"] = self.get_leaders()
        return context

    def get_queryset(self):
        queryset = Topic.objects.annotate(
            num_papers=Count("newspapers")
        ).order_by("-num_papers")
        name = self.request.GET.get("search_text")
        if name:
            return queryset.filter(name__icontains=name)
        return queryset

    def get_leaders(self):
        queryset = self.get_queryset()
        topic_leader = {}
        for topic in queryset:
            redactors_list = list(Redactor.objects.filter(newspapers__topic=topic))
            lead = max(redactors_list, key=redactors_list.count) if redactors_list else "-"
            topic_leader[topic] = lead
        return topic_leader


class TopicDetailView(generic.DetailView):
    model = Topic


class RedactorListView(generic.ListView):
    model = Redactor

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        search_text = self.request.GET.get("search_text", "")
        text = {"search_text": search_text}
        context["search_form"] = SearchForm(initial=text)
        context["favorites"] = self.get_favorites()
        return context

    def get_queryset(self):
        queryset = Redactor.objects.all()
        username = self.request.GET.get("search_text")
        if username:
            return queryset.filter(username__icontains=username)
        return queryset

    def get_favorites(self):
        queryset = self.get_queryset()
        favorite_topic = {}
        for redactor in queryset:
            topic_list = list(Topic.objects.filter(newspapers__publishers=redactor))
            favorite = max(topic_list, key=topic_list.count) if topic_list else "-"
            favorite_topic[redactor] = favorite
        return favorite_topic


class RedactorDetailView(generic.DetailView):
    model = Redactor


class NewspaperListView(generic.ListView):
    model = Newspaper
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        search_text = self.request.GET.get("search_text", "")
        text = {"search_text": search_text}
        context["search_form"] = SearchForm(initial=text)
        context["filter_form"] = NewspaperFilterForm()
        return context

    def get_queryset(self):
        queryset = Newspaper.objects.all()
        title = self.request.GET.get("search_text")
        if title:
            queryset = queryset.filter(title__icontains=title)
        publishers = self.request.GET.get("publishers")
        if publishers:
            queryset = queryset.filter(publishers__in=publishers)
        topic = self.request.GET.get("topic")
        if topic:
            queryset = queryset.filter(topic__in=topic)
        return queryset


class NewspaperDetailView(generic.DetailView):
    model = Newspaper


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = ["name"]

    def get_success_url(self):
        return reverse("tracker:topic-detail", kwargs={"pk": self.object.pk})


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = ["name"]

    def get_success_url(self):
        return reverse("tracker:topic-detail", kwargs={"pk": self.object.pk})


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("tracker:topic-list")


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm

    def get_success_url(self):
        return reverse("tracker:newspaper-detail", kwargs={"pk": self.object.pk})


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm

    def get_success_url(self):
        return reverse("tracker:newspaper-detail", kwargs={"pk": self.object.pk})


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("tracker:newspaper-list")


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorForm

    def get_success_url(self):
        return reverse("tracker:redactor-detail", kwargs={"pk": self.object.pk})


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorForm

    def get_success_url(self):
        return reverse("tracker:redactor-detail", kwargs={"pk": self.object.pk})

templates/tracker/index.html
{% extends "base.html" %}

{% block content %}
{% load static %}
  <div>
    <img style="width:100%;" src="{% static "main_img.jpg" %}" alt="home" />
    <h1>
      <a class="carousel-caption rounded-pill" style="font-size: 1em; background-color: #292d2d; color: lightgrey" href="{% url "tracker:newspaper-create" %}">
        add newspaper
      </a>
    </h1>
  </div>
{% endblock %}

templates/tracker/newspaper_confirm_delete.html
{% extends "base.html" %}
 {% load crispy_forms_filters %}

 {% block content %}
   <div class="mx-auto w-75 p-3">
   <h3>Delete newspaper</h3>
   <br>
   <h6>Are you sure you want to delete {{ newspaper }} newspaper?</h6>
   <form action="" method="post">
   {% csrf_token %}
   {{ form | crispy }}
     <input class="btn-danger"  type="submit" value="Delete">
   </form>
   </div>
 {% endblock %}

templates/tracker/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="mx-auto w-75 p-3">
    <h3>Newspaper: {{ newspaper.title }}</h3>
    <a class="btn-lg" href="{% url "tracker:newspaper-update" pk=newspaper.id%}">Update</a>
    <a class="btn-lg" style="color:red;" href="{% url "tracker:newspaper-delete" pk=newspaper.id%}">Delete</a>
    <p><h6>{{ newspaper.publish_date }}</h6></p>
    {% if newspaper.publishers.all %}
      <p><h6>Redactors:</h6></p>
      <ul>
      {% for redactor in newspaper.publishers.all %}
        <li>
          <a href="{% url "tracker:redactor-detail" pk=redactor.id %}">{{ redactor.username}}</a>
        </li>
      {% endfor %}
      </ul>
    {% endif %}
    <h6>Topics:</h6>
    <ul>
      {% for topic in newspaper.topic.all %}
        <li>
          <a href="{% url "tracker:topic-detail" pk=topic.id %}">{{ topic.name}}</a>
        </li>
      {% endfor %}
      </ul>
  <h4>Content:</h4>
  {{ newspaper.content }}
  </div>
{% endblock %}

templates/tracker/newspaper_form.html
{% extends "base.html" %}
 {% load crispy_forms_filters %}

 {% block content %}
    <div class="mx-auto w-75 p-3">
 <h3>Change Newspapers</h3>
      <br>
   <form action="" method="post" novalidate>
   {% csrf_token %}
   {{ form | crispy}}
   <input type="submit" value="Submit" class="btn btn-primary">
   </form>
    </div>
 {% endblock %}

templates/tracker/newspaper_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container-fluid" style="margin-left: 1em;">
  <div class="row">
  <div class="col-sm-1">
    {% include "includes/sidebar_filter.html" %}
  </div>



  <div class="mx-auto w-75 p-3">
   <form action="" method="get">
    {{ search_form|crispy }}
   </form>


  <div class="container d-flex justify-content-end">
  <h3><a class="btn-lg" href="{% url "tracker:newspaper-create" %}">Add newspaper</a></h3>
  </div>
    {% if newspaper_list %}
      <table class="table ">
        <tr class="thead-light">
          <th>ID</th>
          <th>Title</th>
          <th>Date</th>
        </tr>
      {% for paper in newspaper_list %}
        <tr>
          <td>{{ paper.id }}</td>
          <td><h5><a href={% url "tracker:newspaper-detail" pk=paper.id %}>{{ paper.title }}</a></h5></td>
          <td><h6>{{ paper.publish_date }}</h6></td>
        </tr>
      {% endfor %}
      </table>

  {% else %}
    <br>
    <p>There are no newspapers at the moment </p>
    <br>
      <p>Would you like to <a href="{% url "tracker:newspaper-create" %}">create</a> some? ;)</p>
  {% endif %}
  </div>
  </div>
  </div>
{% endblock %}

templates/tracker/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="mx-auto w-75 p-3">
    <h3>
      {{ redactor.username }}
        <a class="btn-lg" href="{% url "tracker:redactor-update" pk=redactor.id%}">Update</a>
      {% if user == redactor %} (me)
      {% endif %}
    </h3>
    <h6>
      {% if redactor.first_name and redactor.last_name %}
        real name: {{ redactor.first_name }} {{ redactor.last_name }}
      {% endif %}
    </h6>
    <h6>
      {% if redactor.years_of_experience %}
        years of experience: {{ redactor.years_of_experience }}
      {% endif %}
    </h6>
    <br>
    {% if redactor.newspapers.all %}
      <h6>Newspapers:</h6>
      <ul>
      {% for paper in redactor.newspapers.all %}
        <li>
          <a href="{% url "tracker:newspaper-detail" pk=paper.id %}">{{ paper.title}}</a>
          {% if paper.publish_date %}
          <h6>{{ paper.publish_date }}</h6>
          {% endif %}
        </li>
      {% endfor %}
      </ul>
    {% else %}
        <p>This redactor has no newspapers </p>
        <p>Would you like to <a href="{% url "tracker:newspaper-create" %}">create</a> some? ;)</p>
    {% endif %}
  </div>
{% endblock %}

templates/tracker/redactor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="mx-auto w-75 p-3">
   <h3>{{ object|yesno:"Update,Create" }} redactor </h3>
   <br>
   <h6>{{ driver.username }}</h6>
   <br>
   <form action="" method="post" novalidate>
     {% csrf_token %}
     {{ form|crispy }}

     <input type="submit" value="Submit" class="btn btn-primary">
   </form>
  </div>
{% endblock %}

templates/tracker/redactor_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load dict_getter %}
{% block content %}
    <div class="mx-auto w-75 p-3">
      <form action="" method="get">
        {{ search_form|crispy }}
      </form>
      <div class="container d-flex justify-content-end">
  <h3><a class="btn-lg" href="{% url "tracker:redactor-create" %}">Add redactor</a></h3>
  </div>
      <table class="table ">
        <tr class="thead-light">
          <th>ID</th>
          <th>Username</th>
          <th>Real name</th>
          <th>Papers</th>
          <th>Favorite topic</th>
        </tr>
      {% for redactor in redactor_list %}
        <tr>
          <td>{{ redactor.id }}</td>
          <td><h5>
            <a href="{% url "tracker:redactor-detail" pk=redactor.id %}">
            {{ redactor.username }}
            {% if user == redactor %} (me)
            {% endif %}
            </a>
          </h5></td>
          <td> {% if redactor.first_name and redactor.last_name %}
            {{ redactor.first_name }} {{ redactor.last_name }}
            {% endif %} </td>
          <td>{{ redactor.newspapers.count }}</td>
          <td>{{favorites|dict_getter:redactor}}</td>
        </tr>
      {% endfor %}
      </table>
    </div>
{% endblock %}

templates/tracker/topic_confirm_delete.html
{% extends "base.html" %}
 {% load crispy_forms_filters %}

 {% block content %}
   <div class="mx-auto w-75 p-3">
   <h3>Delete topic</h3>
   <br>
   <h6>Are you sure you want to delete {{ topic }} topic?</h6>
   <form action="" method="post">
   {% csrf_token %}
   {{ form | crispy }}
     <input class="btn-danger" type="submit" value="Delete">
   </form>
   </div>
 {% endblock %}

templates/tracker/topic_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="mx-auto w-75 p-3">
    <h3>Topic: {{ topic.name }}</h3>
    <a class="btn-lg" href="{% url "tracker:topic-update" pk=topic.id%}">Update</a>
    <a class="btn-lg" style="color:red;" href="{% url "tracker:topic-delete" pk=topic.id%}">Delete</a>
    <br>
    <br>
    {% if topic.newspapers.all %}
      <h6>Newspapers:</h6>
      <ul>
      {% for paper in topic.newspapers.all %}
        <li>
          <a href="{% url "tracker:newspaper-detail" pk=paper.id %}">{{ paper.title}}</a>
          {% if paper.publish_date %}
          <h6>{{ paper.publish_date }}</h6>
          {% endif %}
        </li>
      {% endfor %}
      </ul>
    {% else %}
      <p>There are no newspapers with such a topic </p>
      <p>Would you like to <a href="{% url "tracker:newspaper-create" %}">create</a> some? ;)</p>
    {% endif %}
  </div>
{% endblock %}

templates/tracker/topic_form.html
{% extends "base.html" %}
 {% load crispy_forms_filters %}

 {% block content %}
    <div class="mx-auto w-75 p-3">
      <h3>Change Topics</h3>
      <br>
      <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form | crispy}}
        <input type="submit" value="Submit" class="btn btn-primary">
      </form>
    </div>
 {% endblock %}

templates/tracker/topic_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load dict_getter %}
{% block content %}
  <div class="mx-auto w-75 p-3">
     <form action="" method="get">
      {{ search_form|crispy }}
     </form>
    {% if topic_list %}
      <div class="container d-flex justify-content-end">
        <h3><a class="btn-lg" href="{% url "tracker:topic-create" %}">Add topic</a></h3>
      </div>
      <table class="table ">
        <tr class="thead-light">
          <th>ID</th>
          <th>Topic</th>
          <th>Papers</th>
          <th>Leader</th>
        </tr>
      {% for topic in topic_list %}
        <tr>
          <td>{{ topic.id }}</td>
          <td><h5><a href="{% url "tracker:topic-detail" pk=topic.id %}">{{ topic.name }}</a></h5></td>
          <td>{{ topic.newspapers.count }}</td>
          <td>{{leaders|dict_getter:topic}}</td>
        </tr>
      {% endfor %}
      </table>
    </div>
  {% else %}
    <br>
    <p>There are no topics at the moment </p>
    <br>
    <p>Would you like to create some? ;)</p>
  {% endif %}
{% endblock %}