django_site_newspaper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
     path("admin/", admin.site.urls),
     path("", include("tracker.urls", namespace="tracker")),
     path("accounts/", include("django.contrib.auth.urls"))
 ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tracker/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from tracker.views import (
    index,
    TopicListView,
    TopicDetailView,
    RedactorListView,
    RedactorDetailView,
    NewspaperListView,
    NewspaperDetailView,
    TopicCreateView,
    NewspaperCreateView,
    TopicUpdateView,
    NewspaperUpdateView,
    TopicDeleteView,
    NewspaperDeleteView,
    RedactorCreateView,
    RedactorUpdateView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list"
     ),
    path(
        "topics/<int:pk>/",
        TopicDetailView.as_view(),
        name="topic-detail"
     ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
     ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
     ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list"
     ),
    path(
         "newspapers/<int:pk>/",
         NewspaperDetailView.as_view(),
         name="newspaper-detail"
     ),
    path(
         "topics/create/",
         TopicCreateView.as_view(),
         name="topic-create"
     ),
    path(
        "newspapers/create/",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "newspapers/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update"
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path(
        "newspapers/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update"
    ),
]

urlpatterns += staticfiles_urlpatterns()

app_name = "tracker"

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
     <div class="navbar-nav nav-fill w-100">
       <h4><a class="nav-link" href="{% url "tracker:index" %}">Home</a></h4>
       <h4><a class="nav-link" href="{% url "tracker:newspaper-list" %}">Newspapers</a></h4>
       <h4><a class="nav-link" href="{% url "tracker:redactor-list" %}">Redactors</a></h4>
       <h4><a class="nav-link" href="{% url "tracker:topic-list" %}">Topics</a></h4>
       {% if user.is_authenticated %}
        <div class="container d-flex justify-content-end">
          <div >
            <h4 class="nav-link"><a href="{% url "tracker:redactor-detail" pk=user.id %}">{{ user.username }}</a></h4>
          </div>
          <div>
            <h4 class="nav-link"><a href="{% url "logout" %}">Log out</a></h4>
          </div>
        {% else %}
          <div class="container d-flex justify-content-end">
             <h4 class="nav-link"><a href="{% url "login" %}">Login</a></h4>
          </div>
        </div>
       {% endif %}
     </div>
   </div>
 </nav>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <div class="mx-auto w-75 p-3">
  <div class="container d-flex justify-content-end">
    <ul class="pagination" >
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number%}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number%}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
  </div>
  </div>
{% endif %}

templates/includes/sidebar_filter.html
{% load crispy_forms_filters %}
<br>
<div class="side">
   <form action="" method="get">
      {{ filter_form|crispy }}
      <input type="submit" value="Filter" class="btn-primary">
    </form>
</div>